### ISSUE TITLE
Windows Implementation Leaves behind CR Chars

### ISSUE THREAD

**Issue by jsuiker** [JoshCheek/sublime-text-2-and-3-seeing-is-believing#20] opened 2017-03-27 17:13 UTC
It all works great aside from the CR characters that remain once the annotations are cleared.  I tried playing with the encoding of the file - making sure to save and reopen as UTF-8.  No juju...

![output_tfahxo](https://cloud.githubusercontent.com/assets/9276566/24368642/2fcbee08-12ef-11e7-8311-4a07b4557ad7.gif)

**Comment by jsuiker** [comment] 2017-03-27 17:25
Not to mention the Peter Pan reference noticed by #19

**Comment by JoshCheek** [comment] 2017-03-27 18:13
Which OS are you on?

**Comment by jsuiker** [comment] 2017-03-27 18:15
I'm a Windows 7 hold-out

**Comment by JoshCheek** [comment] 2017-03-27 18:16
Does Windows 7 not use `"\r\n"` for line ends?

**Comment by JoshCheek** [comment] 2017-03-27 18:19
That was worded confusingly, what I'm saying is that I thought `"\r\n"` was correct on Windows, but it sounds like you are expecting it to just be `"\n"`.

**Comment by jsuiker** [comment] 2017-03-27 18:26
yea i gotcha... \r\n is correct as far as I know.  Interesting thing is that opening the resulting file in notepad and notepad++ shows very different things

![capture](https://cloud.githubusercontent.com/assets/9276566/24371609/527b09e8-12f9-11e7-9d3a-38c6fbc01988.PNG)

**Comment by JoshCheek** [comment] 2017-03-27 18:48
Hmm, RHS is interesting, it's got two CRs on the line. Can you provide files for before, intermediate, and after? Maybe use this program:

```ruby
1
2
```

Eg on my machine, entirely from the terminal it looks like the below screenshot. Yours might differ because you might need to run them from ST to see the issue, also it would differ because you would be using a different shell. As long as I can see the bytes in the file, it should be fine.

![screenshot 2017-03-27 13 43 50](https://cloud.githubusercontent.com/assets/77495/24372423/8634eb7e-12f3-11e7-958e-0f28731f7fed.png)

**Comment by jsuiker** [comment] 2017-03-27 19:22
![binary_capture](https://cloud.githubusercontent.com/assets/9276566/24373979/41d8cd8e-1301-11e7-957f-9bd62296f556.png)

**Comment by JoshCheek** [comment] 2017-03-27 19:47
How interesting! What happens if you run it twice in a row, eg

```ruby
ruby -e 'puts "1\r\n2\r\n"' | seeing_is_believing | seeing_is_believing | ruby -e '$stdin.binmode; p $stdin.read'
"1  # => 1\n2  # => 2\n"
```

I have a hypothesis that it's chomping only the newline on input, but putting the entire "\r\n" on output, if true, it predicts the output will be `"1\r\r\rn2\r\r\rn"`

**Comment by JoshCheek** [comment] 2017-03-27 19:49
I wonder if no one else is experiencing this or if their editors just don't show it to them 🤔

**Comment by jsuiker** [comment] 2017-03-27 19:55
I'm not able to run that set of commands in my environment... but I think I get what you're asking.  I can do Ctrl + Alt + B and Ctrl + Alt + V all day long and it doesn't give me any different output from what I get the first time around.

**Comment by jsuiker** [comment] 2017-03-27 19:59
Oh wait, I used CMD instead of PS and got the following

![cmd_version](https://cloud.githubusercontent.com/assets/9276566/24375491/6b9076cc-1306-11e7-9138-a6fcb888b491.PNG)

**Comment by JoshCheek** [comment] 2017-03-27 20:14
Hmm, not what I was predicting, could be multiple issues. At least it's not in ST, as we bypassed it here. It seems to be between SiB and the OS.

What do you get when you run this code?

```ruby
$ ruby -r english -r pp -e 'pp $INPUT_RECORD_SEPARATOR, $OUTPUT_RECORD_SEPARATOR, ENV.keys.grep(/RUBY|GEM/).map { |k| [k, ENV[k]] }'
```

![screenshot 2017-03-27 15 14 22](https://cloud.githubusercontent.com/assets/77495/24376023/157e6c40-1300-11e7-935f-df53bc5d6d02.png)

**Comment by jsuiker** [comment] 2017-03-27 20:20
"\n"
nil
[]

**Comment by JoshCheek** [comment] 2017-03-27 20:31
Very curious. I would expect that first line to be `"\r\n"` I wonder if it's running through cygwin or some other nix environment. Seems like what's happening is ST and notepad etc all use `"\r\n"` for line ends, but your Ruby is using `"\n"` for some reason, doesn't totally explain everything, but figuring out why that value is `"\n"` instead of `"\r\n"` seems like the obvious place to start. How did you install Ruby?

**Comment by jsuiker** [comment] 2017-03-27 20:33
http://rubyinstaller.org/downloads/

**Comment by JoshCheek** [comment] 2017-03-27 20:43
I'm going to have to wait until I can get on a Windows machine to poke around at it and see if I can reproduce it, I can conceive of too many possibilities, but they're vague enough that I can only describe them abstractly.

**Comment by jsuiker** [comment] 2017-03-27 20:45
haha, now there's a sentence :) Thanks for the help and safe travels!

**Comment by JoshCheek** [comment] 2017-07-06 02:05
Hey, what version of Ruby are you running?

**Comment by JoshCheek** [comment] 2017-07-06 02:05
I've got Windows 7 downloaded, but having difficulty figuring it out.

**Comment by asilano** [comment] 2017-12-13 11:11
I'm seeing this too. Win 7, ruby 2.3.3p222. Ctrl-Z does remove them nicely.

Shout if I can get you more diags.

**Comment by JoshCheek** [comment] 2018-01-21 23:02
Whew, took some effort, but I think I got it. Want to try out the branch `fix-issue-20` and let me know?

**Comment by JoshCheek** [comment] 2018-01-21 23:05
Ehh, fuckit, I just merged it. If you have issues, LMK.

**Closed** 2018-01-21 23:04 UTC
